### ISSUE TITLE
咨询duration参数设定

### ISSUE THREAD

**Issue by dejin** [mqhe2007/aliyunddns#1]
Hi Qingjin：

您好，我想咨询一下duration参数的用法，因为我没有任何go语言基础，所以看不明白这个参数，我猜这个参数是设定更新ddns的时间间隔，默认的12是12小时更新一次，如果我想加快其更新，设置"duration": 0.1 是不是可以0.1小时就更新一次？如果不是，想设置10分钟更新一次，该如何设置啊？非常感谢！

BR，
Dejin

**Comment by mqhe2007** [comment]
@dejin 您好，最近我对此工具进行了重构，支持[Cron表达式](https://en.wikipedia.org/wiki/Cron)进行定时任务控制，最小时间间隔可以控制到”秒“级（但是不推荐这么做）。
感谢使用！
